//! A mock llama.cpp server used by the integration tests and the
//! `mock_llama` example for local smoke testing.
//!
//! Implements the subset of the llama.cpp HTTP API used by the proxy:
//! - `GET  /v1/models`
//! - `POST /v1/chat/completions` (JSON or SSE stream; configurable status,
//!   raw non-JSON body, and per-chunk delay)
//! - `POST /slots/:slot_id?action=save|restore` (JSON body `{"filename": ...}`)

use axum::Json;
use axum::Router;
use axum::body::Body;
use axum::extract::{Path, Query, State};
use axum::http::{StatusCode, header};
use axum::response::{IntoResponse, Response};
use axum::routing::{get, post};
use bytes::Bytes;
use futures::{StreamExt, stream};
use serde_json::{Value, json};
use std::net::SocketAddr;
use std::sync::Arc;
use std::sync::atomic::{AtomicU16, AtomicU64, AtomicUsize, Ordering};
use std::time::Duration;
use tokio::net::TcpListener;
use tokio::sync::Mutex;

/// Everything the mock observed, plus the per-request results.
#[derive(Debug, Default, Clone)]
pub struct MockCalls {
    pub chat_bodies: Vec<Value>,
    pub chat_queries: Vec<Vec<(String, String)>>,
    pub saves: Vec<(usize, String)>,
    pub restores: Vec<(usize, String)>,
}

pub struct MockState {
    pub model_id: String,
    /// If non-zero, chat completions respond with this HTTP status.
    pub chat_status: AtomicU16,
    /// If non-zero, slot save responds with this HTTP status.
    pub save_status: AtomicU16,
    /// If non-zero, slot restore responds with this HTTP status.
    pub restore_status: AtomicU16,
    /// Delay between streamed SSE chunks, in milliseconds.
    pub stream_chunk_delay_ms: AtomicU64,
    /// Number of SSE chunks the mock has produced so far (emulates tokens
    /// generated by the backend). Lets a test observe whether the client
    /// (the proxy) aborted the stream: after an abort no further chunks are
    /// produced.
    pub chunks_produced: AtomicUsize,
    /// Delay (ms) before the non-streaming JSON body is produced (0 =
    /// immediate, the default). Emulates a long-running generation so a test
    /// can observe whether the client (the proxy) aborted the request.
    pub chat_body_delay_ms: AtomicU64,
    /// Number of non-streaming JSON bodies produced so far.
    pub json_bodies_produced: AtomicUsize,
    /// When set, chat completions return this raw `(content_type, body)`
    /// instead of the normal JSON/SSE response.
    pub raw_response: Mutex<Option<(String, String)>>,
    /// When set, successful saves create a file `<save_dir>/<filename>`
    /// (emulates the backend's `--slot-save-path` directory).
    pub save_dir: Option<std::path::PathBuf>,
    pub calls: Mutex<MockCalls>,
}

impl MockState {
    pub fn new(model_id: impl Into<String>) -> Arc<Self> {
        Self::with_save_dir(model_id, None)
    }

    pub fn with_save_dir(
        model_id: impl Into<String>,
        save_dir: Option<std::path::PathBuf>,
    ) -> Arc<Self> {
        Arc::new(Self {
            model_id: model_id.into(),
            chat_status: AtomicU16::new(0),
            save_status: AtomicU16::new(0),
            restore_status: AtomicU16::new(0),
            stream_chunk_delay_ms: AtomicU64::new(0),
            chunks_produced: AtomicUsize::new(0),
            chat_body_delay_ms: AtomicU64::new(0),
            json_bodies_produced: AtomicUsize::new(0),
            raw_response: Mutex::new(None),
            save_dir,
            calls: Mutex::new(MockCalls::default()),
        })
    }

    pub async fn set_raw_response(&self, content_type: &str, body: &str) {
        *self.raw_response.lock().await = Some((content_type.to_string(), body.to_string()));
    }

    pub async fn clear_raw_response(&self) {
        *self.raw_response.lock().await = None;
    }

    /// Delay between streamed SSE chunks (for tests).
    pub fn set_stream_chunk_delay(&self, d: Duration) {
        self.stream_chunk_delay_ms
            .store(d.as_millis() as u64, Ordering::SeqCst);
    }

    /// Delay before the non-streaming JSON body is produced (for tests).
    pub fn set_chat_body_delay(&self, d: Duration) {
        self.chat_body_delay_ms
            .store(d.as_millis() as u64, Ordering::SeqCst);
    }

    pub async fn chat_bodies(&self) -> Vec<Value> {
        self.calls.lock().await.chat_bodies.clone()
    }

    pub async fn chat_queries(&self) -> Vec<Vec<(String, String)>> {
        self.calls.lock().await.chat_queries.clone()
    }

    pub async fn saves(&self) -> Vec<(usize, String)> {
        self.calls.lock().await.saves.clone()
    }

    pub async fn restores(&self) -> Vec<(usize, String)> {
        self.calls.lock().await.restores.clone()
    }

    /// Number of SSE chunks produced so far (see [`MockState::chunks_produced`]).
    pub fn chunks_produced(&self) -> usize {
        self.chunks_produced.load(Ordering::SeqCst)
    }

    pub fn reset_chunks_produced(&self) {
        self.chunks_produced.store(0, Ordering::SeqCst);
    }

    /// Number of non-streaming JSON bodies produced so far.
    pub fn json_bodies_produced(&self) -> usize {
        self.json_bodies_produced.load(Ordering::SeqCst)
    }

    pub fn reset_json_bodies_produced(&self) {
        self.json_bodies_produced.store(0, Ordering::SeqCst);
    }
}

/// A running mock llama.cpp server on a local port.
pub struct MockLlama {
    pub state: Arc<MockState>,
    pub addr: SocketAddr,
    _handle: tokio::task::JoinHandle<()>,
}

impl MockLlama {
    /// Start on a random local port (127.0.0.1:0).
    pub async fn start(model_id: &str) -> Self {
        let addr: SocketAddr = "127.0.0.1:0".parse().expect("literal addr");
        Self::start_on(model_id, addr).await
    }

    /// Like [`MockLlama::start`], but successful saves also create a KV
    /// file in `dir` (emulates `--slot-save-path`).
    pub async fn start_with_save_dir(model_id: &str, dir: impl Into<std::path::PathBuf>) -> Self {
        let addr: SocketAddr = "127.0.0.1:0".parse().expect("literal addr");
        Self::start_on_with_save_dir(model_id, addr, Some(dir.into())).await
    }

    /// Start on a specific address.
    pub async fn start_on(model_id: &str, addr: SocketAddr) -> Self {
        Self::start_on_with_save_dir(model_id, addr, None).await
    }

    /// Start on a specific address; when `dir` is set, successful saves
    /// also create a KV file there (emulates `--slot-save-path`).
    pub async fn start_on_with_save_dir(
        model_id: &str,
        addr: SocketAddr,
        dir: Option<std::path::PathBuf>,
    ) -> Self {
        let state = match dir {
            Some(d) => MockState::with_save_dir(model_id, Some(d)),
            None => MockState::new(model_id),
        };
        let app = Router::new()
            .route("/v1/models", get(models_handler))
            .route("/v1/chat/completions", post(chat_handler))
            .route("/slots/{slot_id}", post(slot_handler))
            .with_state(state.clone());
        let listener = TcpListener::bind(addr)
            .await
            .expect("bind mock llama server");
        let addr = listener.local_addr().expect("local addr");
        let handle = tokio::spawn(async move {
            let _ = axum::serve(listener, app).await;
        });
        Self {
            state,
            addr,
            _handle: handle,
        }
    }

    /// Base URL for the client, e.g. `http://127.0.0.1:54321`.
    pub fn url(&self) -> String {
        format!("http://{}", self.addr)
    }

    /// Stop the mock (abort the server task); the port is released.
    pub fn stop(self) {
        self._handle.abort();
    }
}
async fn models_handler(State(st): State<Arc<MockState>>) -> impl IntoResponse {
    Json(json!({ "data": [{ "id": st.model_id }] }))
}

async fn chat_handler(
    State(st): State<Arc<MockState>>,
    Query(q): Query<Vec<(String, String)>>,
    Json(body): axum::Json<Value>,
) -> Response {
    {
        let mut calls = st.calls.lock().await;
        calls.chat_bodies.push(body.clone());
        calls.chat_queries.push(q);
    }

    let status = st.chat_status.load(Ordering::SeqCst);
    if status != 0 {
        let code = StatusCode::from_u16(status).unwrap_or(StatusCode::INTERNAL_SERVER_ERROR);
        return (code, axum::Json(json!({ "error": "mock chat failure" }))).into_response();
    }

    if let Some((ctype, raw)) = st.raw_response.lock().await.take() {
        let mut resp = axum::http::Response::new(Body::from(raw));
        resp.headers_mut().insert(
            header::CONTENT_TYPE,
            ctype.parse().expect("valid content type"),
        );
        return resp;
    }

    let is_stream = body.get("stream").and_then(Value::as_bool).unwrap_or(false);
    if is_stream {
        let delay = Duration::from_millis(st.stream_chunk_delay_ms.load(Ordering::SeqCst));
        let st2 = st.clone();
        let events: Vec<String> = vec![
            "data: {\"id\":\"chatcmpl-mock\",\"object\":\"chat.completion.chunk\",\"choices\":[{\"index\":0,\"delta\":{\"role\":\"assistant\",\"content\":\"Hello\"}}]}\n\n"
                .to_string(),
            "data: {\"id\":\"chatcmpl-mock\",\"object\":\"chat.completion.chunk\",\"choices\":[{\"index\":0,\"delta\":{\"content\":\" world\"}}]}\n\n"
                .to_string(),
            "data: [DONE]\n\n".to_string(),
        ];
        let s = stream::iter(events).then(move |e| {
            let st2 = st2.clone();
            async move {
                if !delay.is_zero() {
                    tokio::time::sleep(delay).await;
                }
                // "generated" this chunk; if the client aborts the
                // connection, this stream is dropped and no further chunks
                // are produced
                st2.chunks_produced.fetch_add(1, Ordering::SeqCst);
                Ok::<Bytes, std::io::Error>(Bytes::from(e))
            }
        });
        let mut resp = axum::http::Response::new(Body::from_stream(s));
        resp.headers_mut().insert(
            header::CONTENT_TYPE,
            "text/event-stream".parse().expect("valid content type"),
        );
        resp.headers_mut().insert(
            header::CACHE_CONTROL,
            "no-cache".parse().expect("valid cache control"),
        );
        return resp;
    }

    let reply = json!({
        "id": "chatcmpl-mock",
        "object": "chat.completion",
        "model": body.get("model").cloned().unwrap_or(json!("mock-model")),
        "choices": [{
            "index": 0,
            "message": { "role": "assistant", "content": "mock reply" },
            "finish_reason": "stop"
        }],
        "usage": { "prompt_tokens": 1, "completion_tokens": 2, "total_tokens": 3 }
    });
    let delay_ms = st.chat_body_delay_ms.load(Ordering::SeqCst);
    if delay_ms == 0 {
        return axum::Json(reply).into_response();
    }
    // Long-running generation: the headers go out immediately, the (single)
    // JSON body only after `delay_ms`. If the client aborts the connection
    // during the delay, this stream is dropped and the body is never
    // produced (json_bodies_produced stays 0).
    let st2 = st.clone();
    let s = stream::iter(vec![reply]).then(move |v| {
        let st2 = st2.clone();
        async move {
            tokio::time::sleep(Duration::from_millis(delay_ms)).await;
            st2.json_bodies_produced.fetch_add(1, Ordering::SeqCst);
            let bytes = serde_json::to_vec(&v).expect("json encode");
            Ok::<Bytes, std::io::Error>(Bytes::from(bytes))
        }
    });
    let mut resp = axum::http::Response::new(Body::from_stream(s));
    resp.headers_mut().insert(
        header::CONTENT_TYPE,
        "application/json".parse().expect("valid content type"),
    );
    resp
}

async fn slot_handler(
    State(st): State<Arc<MockState>>,
    Path(slot_id): Path<usize>,
    Query(q): Query<Vec<(String, String)>>,
    Json(body): axum::Json<Value>,
) -> Response {
    let action = q
        .iter()
        .find(|(k, _)| k == "action")
        .map(|(_, v)| v.clone())
        .unwrap_or_default();
    let filename = body
        .get("filename")
        .and_then(Value::as_str)
        .unwrap_or_default()
        .to_string();
    let status = match action.as_str() {
        "save" => {
            st.calls
                .lock()
                .await
                .saves
                .push((slot_id, filename.clone()));
            st.save_status.load(Ordering::SeqCst)
        }
        "restore" => {
            st.calls
                .lock()
                .await
                .restores
                .push((slot_id, filename.clone()));
            st.restore_status.load(Ordering::SeqCst)
        }
        _ => return StatusCode::BAD_REQUEST.into_response(),
    };
    let code = StatusCode::from_u16(if status == 0 { 200 } else { status })
        .unwrap_or(StatusCode::INTERNAL_SERVER_ERROR);
    if action == "save"
        && code == StatusCode::OK
        && let Some(dir) = &st.save_dir
    {
        // emulate llama.cpp writing the KV file to --slot-save-path
        let _ = std::fs::create_dir_all(dir);
        let _ = std::fs::write(dir.join(&filename), b"mock-kv");
    }
    (code, axum::Json(json!({ "ok": true }))).into_response()
}
